### ISSUE TITLE
How can get channel name from MessageEvent? 

### ISSUE THREAD

**Issue by eggcaker** [shomali11/slacker#102]
How can get a channel name (#genenal like )  when received event? right now seems only channel id can read from even.

**Comment by arusso** [comment]
This will soon accessible directly from the `MessageEvent` struct once #100 is merged in, but for now you should be able to get it with something like this:

```
chan, _ := ctx.client.GetConversationInfo(ctx.Event().Channel)
// chan.Name should contain the name of the channel / dm you're in
```
