### ISSUE TITLE
Create releases for Slacker

### ISSUE THREAD

**Issue by arusso** [shomali11/slacker#105]
It would be helpful to cut releases for Slacker that make it easy for users to pin to a particular versions (and not the auto-generated versions go creates) and provide release notes for each release.

While this isn't something that we'll be doing often, it's also easy to do with [goreleaser](https://github.com/goreleaser/goreleaser) and improves the quality of the project imo.

**Comment by arusso** [comment]
@shomali11 any objections to this?

My intentions is to tag 313e72e3ec6ff839cdc9a1a28267b3941d05704e as v0.0.99 and then tag this merge commit as v0.1.0 once it gets merged in. That's primarily to make the generated changelog cleaner.

**Comment by shomali11** [comment]
Great idea! Thank you for this!
