### ISSUE TITLE
Websocket stoped work due an update from Slack Team

### ISSUE THREAD

**Issue by evandroflores** [shomali11/slacker#11]
Slack Team started to return a [query string parameter with their websocket URLs](https://api.slack.com/changelog/2018-01-dont-let-websocket-uris-with-query-strings-get-you-down), and the current version of [nslopes/slack](https://github.com/nslopes/slack) stopped work. After this [pull request merge](https://github.com/nlopes/slack/pull/217) [nslopes/slack](https://github.com/nslopes/slack) started to work again.

Here is a PR (#9) that aims to fix the version on [shomali11/slacker](https://github.com/shomali11/slacker).

**Comment by shomali11** [comment]
Thank you for putting the PR together. I merged it.
