### ISSUE TITLE
Allow ability to define a Default Inner Event Handler

### ISSUE THREAD

**Issue by broxgit** [shomali11/slacker#112]
It would be largely beneficial to be able to define a Default Inner Event Handler similar to how we define a defaultEventHandler. 

This would allow custom handling for events such as: 
- member_joined_channel
- member_left_channel
- group_left
- group_deleted
etc... 

I would like to submit a pull request for this, I have a branch ready to go

**Comment by arusso** [comment]
Are you talking about being able to specify a custom `handleMessageEvent`?

If so that seems worthwhile. I should have time in the next week to review a PR.

**Comment by broxgit** [comment]
I can't push my branch but if I can get access to push, I can show you the quick and easy change.

**Comment by arusso** [comment]
Can you fork the repo and submit a PR from your fork?

**Comment by broxgit** [comment]
https://github.com/shomali11/slacker/pull/113/files?diff=unified&w=1

**Comment by arusso** [comment]
Closed by #113
