### ISSUE TITLE
panic: runtime error when adding DispatchActionConfig.TriggerActionsOn NewPlainTextInputBlockElement

### ISSUE THREAD

**Issue by alex8bitw** [shomali11/slacker#119]
This works:
```
textElement := slack.NewPlainTextInputBlockElement(textPlaceholder, "bulkemails")
textElement.MaxLength = 2500
textElement.Multiline = true
```
But when I add:
```
var actions []string = []string{"on_enter_pressed"}

textElement.DispatchActionConfig.TriggerActionsOn = actions
```

I get:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8193c4]
```

I've tried updating to the latest slack-go/slack API and still have the issue.  It seems to be supported upstream:  https://github.com/slack-go/slack/blob/03f86be11aa50ac65d66f3917e250d3257389028/block_element.go#L409

**Comment by arusso** [comment]
It doesn't look like you're even touching slacker, so perhaps this should be filed with the go-slack folks?

If you think this is a slacker issue can please provide a more complete example that I can use to reproduce the issue.

**Comment by alex8bitw** [comment]
Yep, upstream issue, although technically a configuration problem with slack-go.
