### ISSUE TITLE
How do you handle slash commands

### ISSUE THREAD

**Issue by xorima** [shomali11/slacker#124]
Hi,

I'm trying to understand how slash commands work, I can see from pr: https://github.com/shomali11/slacker/pull/100 that support was added and that example 18 was made, but this example really isn't clear on how to configure these

tl;dr: 
How do I action `/mycommand` using this framework

**Comment by arusso** [comment]
Are you asking how to implement one in slacker or how to configure the Slack App to register the slash command?

**Comment by xorima** [comment]
@arusso how to implement one in slacker

**Comment by xorima** [comment]
@arusso any chance you had to look into this? Else I might just see if chatgpt can figure it out tonight 😅

**Comment by arusso** [comment]
I think this is probably the most basic example I can provide: https://github.com/shomali11/slacker/tree/master/examples/slash-cmd/main.go

One thing to note is that you do not include the leading `/` when defining the command in slacker. So a command of `/ping` would be defined as `ping`. You can see that in the example [here](https://github.com/shomali11/slacker/blob/master/examples/slash-cmd/main.go#L21).
