### ISSUE TITLE
Please don't break your API for an aesthetic change without going to v2...

### ISSUE THREAD

**Issue by yunginnanet** [shomali11/slacker#127]
[We don't do this in go](https://go.dev/doc/modules/release-workflow#breaking).

I'm sure you can see why.

This was not a good decision.

**Comment by arusso** [comment]
Agreed and sorry about the breakage.

@shomali11 and I have been discussing this and I'm working on documenting a release process to prevent this going forward.

**Comment by yunginnanet** [comment]
Thanks for acknowledging, godspeed.
