### ISSUE TITLE
Getting all command arguments

### ISSUE THREAD

**Issue by otto-md** [shomali11/slacker#13]
Thanks for a nice library!

I wanted to create a command like this one:
```go
bot.Command("alert <msg>", "Set the system alert msg. Example: `@deployprod alert Today at noon ...`", alert(bot))
```

If I use `alert := request.Param("msg")` I only get the first word `Today` not all the words `Today at noon ...`.

I can parse it out from `request.Event.Msg.Text`, but it would be nice if there was an easy way to get it. Perhaps from the `slacker.Request`?

**Comment by shomali11** [comment]
I appreciate your kindness!

You are right. I will work on a fix to make this possible :)

**Comment by shomali11** [comment]
I pushed a recent update that addresses this case.

Now <msg> should contain the entire "Today at noon ..." instead of the first word

**Comment by otto-md** [comment]
Thanks, it works as expected.
