### ISSUE TITLE
Regression of issue #84, cannot use library to read/respond to message events from other bots 

### ISSUE THREAD

**Issue by troyxmccall** [shomali11/slacker#135]
hi, having trouble figuring out exactly _when_ this happened, but looks like #84 was re-introduced due some refactoring:

https://github.com/shomali11/slacker/blame/9ac386d1945fda8174e22989b18b4a4d630774bd/message_event.go#L111-L117

ps: love this library, and have really enjoyed using it to build my bots

**Comment by arusso** [comment]
Looks like d3d36ce8fb8cf7a9110034b02acf671ad6a37146 introduced the regression.

**Comment by troyxmccall** [comment]
@arusso awesome, ty

I've confirmed it's these lines on my fork:


https://github.com/troyxmccall/slacker/commit/547f5b9826be244fdee876e04f32c31c70600b69#diff-39212194d5ee67b42e27d469d1eeebab515c5d6b5c13d5d143feba4c567d5ef9L111-L117

here's a test from a webhook app, and my bot (using slacker), the furies, responding (the desired result):

![test](https://user-images.githubusercontent.com/129784/231763918-ac3589b8-fb30-400e-bd78-0323ba78ece1.png)
