### ISSUE TITLE
Send message to another user / expose RTM

### ISSUE THREAD

**Issue by otto-md** [shomali11/slacker#14]
Hi again,

I want to send a message to another user (not the one that sent the command) from the bot.

Using the `nlopes/slack` api I would do `rtm.OpenIMChannel(userID)` followed by `rtm.SendMessage(rtm.NewOutgoingMessage("hello", userChannel))`.

But right now the only the `Client` is exposed in the Slacker struct. Could the rtm be exported too? Or is there another way of doing this?

**Comment by shomali11** [comment]
That’s a nice idea.

The RTM could be exposed but I would like to hide low level implementation details and try my best to provide a simpler method.

Perhaps we can introduce a “ReplyTo” function where the ID of the channel/user is passed along with the message?

**Comment by otto-md** [comment]
Sure, a `ReplyTo` would be nice.

But I also want to try to implement more advanced [interactive features](https://medium.com/mercari-engineering/writing-an-interactive-message-bot-for-slack-in-golang-6337d04f36b9). And then I think having access to the low level api might become necessary.

**Comment by shomali11** [comment]
Fair enough.

You are welcome to create a PR to do so. It should be straightforward.

I am already exposing the “Client” as seen in example7.go

If you are not in a hurry, I can take care of it as soon as possible later today.

**Comment by shomali11** [comment]
I have updated the framework to expose RTM.

Please check example7.go to see how you can access it

**Comment by otto-md** [comment]
Thanks for doing this, it was night here so you beat me to it :)
