### ISSUE TITLE
Multiline command not working

### ISSUE THREAD

**Issue by vikas-karadia** [shomali11/slacker#144]
To describe the issue
I am trying to build a bot and it is working fine when I do it using a single line command
`ctx.Request().Param("command")`
but when I use the same code for multi line command it only takes out the first line

**Comment by raed-shomali** [comment]
I am not sure we thought of multi-line input support. Could you share the case you need to support?

**Comment by arusso** [comment]
We've moved this repo to github.com/slack-io/slacker. If this is still an issue please re-submit the issue there. Apologies for the inconvenience.
