### ISSUE TITLE
Remove vendored slack package

### ISSUE THREAD

**Issue by neonima** [shomali11/slacker#15]
So that we can call the RTM func with all the power of the nlopes/slack library. 

I.E. `bot.Client.SendMessageContext(context.Background(), request.Event.Channel, slack.MsgOptionAttachments(attachments...))` which is not possible because it tries to compare to the vendored library.

**Comment by neonima** [comment]
Yes sure, `slack.MsgOptionAttachments` coupled with `SendMessageContext` isn't possible at the moment because it tries to compare your vendored nlopes/slack with the one I'm using.

```go
for{
		attachment := slack.Attachment{
			Pretext: "Humans don't have memory",
			Title:   watcher.Server,
			Text:    fmt.Sprintf("Ping: %v \n SSH: %v \n Web: %v", watcher.Checks.Ping.Active, watcher.Checks.SSH.Active, strings.Join(watcher.Checks.Webs.EndPoints, " - ")),
			Color:   color,
		}
		attachments = append(attachments, attachment)
}
bot.Client.SendMessageContext(context.Background(), request.Event.Channel, slack.MsgOptionAttachments(attachments...))
```

**Comment by jvrplmlmn** [comment]
This was solved by https://github.com/shomali11/slacker/pull/23 / https://github.com/shomali11/slacker/commit/e68b061d68c25d75dfcfcb177f9298bb9cd77fb4
