### ISSUE TITLE
How to bind a command to all messages?

### ISSUE THREAD

**Issue by kerma** [shomali11/slacker#150]
I've been reading some older examples and v1.4 code, but still struggling to figure out how to create a command which reacts to all messages, regardless whether there is a @botmention prefix present. 

Couple of use cases for it:
- start a thread with @botmention, bot posts reply to thread, all further messages are treated as additional commands 
- follow chat messages, react when a some word is mentioned (like slackbot does it)
- allow commands to be sent without @botmention prefix in private messages
- allow conversational AI chat 

Any pointers how to achieve those things today, or maybe in v2? As far as I can tell most of the mechanism is there. So maybe I'm just missing an example on how to use a custom Command with a Match(string) that always succeeds?

**Comment by sheldonhull** [comment]
related. I'm wondering the same thing. Detecting and continuing a reply is something I'd like to figure out. 

https://github.com/shomali11/slacker/discussions/143

**Comment by raed-shomali** [comment]
I am trying to get clarification on the desired result.

Currently, Slacker allows you to create bots that can respond if you mention them in a channel/group or in a private message. 

If you to talk to the bot in a private message, you do not need to explicitly mention it.

It does not support the first case, as the intention was for the bot to respond only when explicitly called upon in a public channel or group.

**Comment by sheldonhull** [comment]
Right now I'm doing this via just including the alias `!gpt` anywhere in the conversation. Then I include every message each time from the thread (or just the message in the first unthreaded instance).

it's working well and not too much effort to include. Originally I meant for a threaded message started mentioning the bot to automatically handle each message and respond without further mention. 
I think for now that I'm happy with the alias mention to better control it. 


if useful I'd be glad to provide an example of how I'm doing it if it's useful

**Comment by arusso** [comment]
We've moved this repo to github.com/slack-io/slacker. If this is still an issue please re-submit the issue there. Apologies for the inconvenience.
