### ISSUE TITLE
Provide ability to handle block_suggestion events appropriatly

### ISSUE THREAD

**Issue by 0xArch3r** [shomali11/slacker#152]
i forked this repo and made a version that has this fix https://github.com/0xArch3r/slacker/releases/tag/v2.0.3

**Comment by raed-shomali** [comment]
Could you clarify why `block_suggestion` needs a different way of handling?

**Comment by arusso** [comment]
We've moved this repo to github.com/slack-io/slacker. If this is still an issue please re-submit the issue there. Apologies for the inconvenience.
