### ISSUE TITLE
BotModeIgnoreApp fails to handle the official SlackBot

### ISSUE THREAD

**Issue by rk295** [shomali11/slacker#158]
When using `BotModeIgnoreApp` the framework ignores messages from the official SlackBot, logging this error:

```
DEBU[0074] message from a bot with BotID: B01           
DEBU[0074] unable to get information on the bot that sent message: bot_not_found 
```

First line there was from some extra debug I added while triaging the issue.

The root cause is [this](https://github.com/slackapi/python-slack-sdk/issues/1260), in short the API returns an error if you lookup the special case `B01` which is reserved for the official bot. Neither the API of the Go Package we rely on handles this for us, so we must special case it in our code.

**Comment by arusso** [comment]
We've moved this repo to github.com/slack-io/slacker. If this is still an issue please re-submit the issue there. Apologies for the inconvenience.
