### ISSUE TITLE
Using a different implementation of ResponseWriter in handleMessage?

### ISSUE THREAD

**Issue by jvrplmlmn** [shomali11/slacker#17]
### Context

Even though a Command has a `handler` function that receives a ResponseWriter interface:

https://github.com/shomali11/slacker/blob/a253fd241fe23942b2497549aedbbb3d195988bb/command.go#L18

`handleMessage` uses a implementation of ResponseWriter, Response:

https://github.com/shomali11/slacker/blob/a253fd241fe23942b2497549aedbbb3d195988bb/slacker.go#L140-L158

### Question

What is the suggested approach to use a different implementation of ResponseWriter?

**Comment by shomali11** [comment]
Good question. I believe this is the PR that introduced the ResponseWriter interface
https://github.com/shomali11/slacker/pull/3

It has a good example provided with it that could help you with what you are trying to do.
If you can think of a better way to do this, you are more than welcome to put together a PR to solve this. It would be very much appreciated.

**Comment by shomali11** [comment]
I put together support for custom response writer.
You can check it out here: https://github.com/shomali11/slacker/blob/master/examples/example10.go
