### ISSUE TITLE
Not able to get a response using the slack token

### ISSUE THREAD

**Issue by Niraj-Fonseka** [shomali11/slacker#25]
I've been trying to get the ping program running by using a the Slack bot token. I was able to get this working before but it doesn't seem to work anymore. Is anyone else experiencing this ?

**Comment by shomali11** [comment]
Perhaps the token you used was invalidated? Could you login to Slack and verify that the token is valid?

I just tried one of the examples with a valid token of mine and it works fine.

**Comment by Niraj-Fonseka** [comment]
It was actually a proxy issue on my end ! Thanks for checking this on your end and for the quick response though. Closing the issue
