### ISSUE TITLE
Creating a command with multiple long parameters

### ISSUE THREAD

**Issue by jaxxstorm** [shomali11/slacker#27]
I'd like to create a command like so:

```
@bot <summary> <description>
```

Where I can specify summary as `"my summary"` and description as `"my description"` with the quotation marks there.

Is this possible to do?

**Comment by shomali11** [comment]
Hello, `slacker` currently relies on https://github.com/shomali11/commander to parse commands like those.

It currently does not support quoted parameters like those. However, you could probably be able to do something like this:

```
@bot summary <summary> description <description>
```

It should match everything between the words `summary` and `description` to be the value of <summary> and everything after `description` to be the value for <description>

**Comment by shomali11** [comment]
So something like:

`@bot summary What do we need to do? description We need to take care of this and that`

`<summary>` will be assigned `What do we need to do?`
`<description>` will be assigned `We need to take care of this and that`

**Comment by jaxxstorm** [comment]
Perfect, thanks!
