### ISSUE TITLE
Feature Request: AuthFunc callback for dynamic auth determination

### ISSUE THREAD

**Issue by ayjayt** [shomali11/slacker#35]
* CommandDefinition taking an `AuthFunc(slacker.Request) bool` that decides if command is auth'd and returns true or false

I will implement this today on my fork but I was looking for feedback if you had it/were interested in it.

**Comment by shomali11** [comment]
If I understand correctly, this method would replace the existing ability to check whether a user is among the authorized users to execute a command. Would this be a way to authenticate a user against some different mechanism not related to Slack?

I like it. I believe it can be very useful.

Thank you very much for coming up with this great idea
