### ISSUE TITLE
Implement cross usage of Block Kit with similar interface as WithAttachments()

### ISSUE THREAD

**Issue by pschwartz** [shomali11/slacker#46]
Block Kit is the next evolution of message response ui for slack.

https://api.slack.com/block-kit

Using Block Kit a user can create reusable ui blocks and templates. Support for Block kit was added to nlopes/slack from mid February to the end of March.

**Comment by pschwartz** [comment]
Code to implement this has been merged.

**Comment by alex8bitw** [comment]
Could we get an example of using the block kit with Slacker?  I'm able to create blocks, but I'm having issues getting the input text from different blocks.
