### ISSUE TITLE
Installation failing due to recent change

### ISSUE THREAD

**Issue by mathew-fleisch** [shomali11/slacker#48]
I was trying to install slacker in an empty project and got the following error:
`../../pkg/mod/github.com/shomali11/slacker@v0.0.0-20190517235146-8c6fbe523fc5/defaults.go:51:16: undefined: slack.Block`

**Comment by shomali11** [comment]
I recently merged a PR by a collaborator who added a new feature to support `slack.Block` but the dependencies might not have been properly updated. I just did that.

Could you confirm that everything is working fine with you?

**Comment by mathew-fleisch** [comment]
Thanks for getting back to me. I tried to install again, and am still getting a similar error:
`$ go get github.com/shomali11/slacker
go: finding github.com/shomali11/slacker latest
go: finding github.com/shomali11/proper latest
go: finding github.com/shomali11/commander latest
# github.com/shomali11/slacker
../../pkg/mod/github.com/shomali11/slacker@v0.0.0-20190520215100-94c583a09447/defaults.go:51:16: undefined: slack.Block`

**Comment by shomali11** [comment]
Try using dep instead of go get

The project probably needs to be using go modules in order for a smoother use of go get

**Comment by mathew-fleisch** [comment]
I can try that again. I have never used dep before, and hit a config error when I tried it at first. I was trying to use the built-in `go mod init project` to manage my go modules rather than relying on an external package manager. My colleague seems to think the dependency issue might be because you're not using the semver version convention. Just a guess. ¯\_(ツ)_/¯ Here's what the go.mod file looks like:
```
module github.com/example/custombot

go 1.12

require (
  github.com/gorilla/websocket v1.4.0 // indirect
  github.com/nlopes/slack v0.5.0 // indirect
  github.com/pkg/errors v0.8.1 // indirect
  github.com/shomali11/commander v0.0.0-20190312174449-57e7c4df59d6 // indirect
  github.com/shomali11/proper v0.0.0-20180607004733-233a9a872c30 // indirect
  github.com/shomali11/slacker v0.0.0-20190520215100-94c583a09447
)
```

**Comment by shomali11** [comment]
Thanks to @jvrplmlmn now `slacker` has been updated to use Go Modules
