### ISSUE TITLE
RTM Error when processing events

### ISSUE THREAD

**Issue by andysnowden** [shomali11/slacker#52]
Hello,

For the last few days the slacker library has been unable to process RTM events.  Not sure if this is due to a bug or a upstream change by slack.

Debug Log
`nlopes/slack2019/11/25 12:49:36 websocket_managed_conn.go:471: RTM Error, could not unmarshall event "message": {"client_msg_id":"a5dd84e7-de31-4988-b295-7c71a65b1f30","suppress_notification":false,"type":"message","text":"<@UCDV3PDHA> help","user":"UDB261B46","team":"T041L0Z03","blocks":[{"type":"rich_text","block_id":"f76c","elements":[{"type":"rich_text_section","elements":[{"type":"user","user_id":"UCDV3PDHA"},{"type":"text","text":" help"}]}]}],"user_team":"T041L0Z03","source_team":"T041L0Z03","channel":"DD9FTPJE8","event_ts":"1574704175.007700","ts":"1574704175.007700"}
`

Since you are dropping the actual error from json.Unmarshal I added it and see the following:
`2019/11/25 12:49:36 unsupported block type`

LMK what other information you might need to troubleshoot.

**Comment by andysnowden** [comment]
Appears the parent library also had this issue

https://github.com/nlopes/slack/issues/630

**Comment by shomali11** [comment]
Thank you for bringing this up!

I just updated the nlopes dependencies. It seems to be working now.
