### ISSUE TITLE
Is it possible to send a message to a channel without a command from user?

### ISSUE THREAD

**Issue by cis-nothize** [shomali11/slacker#55]
Such as some notification system would send a message to a channel.

**Comment by shomali11** [comment]
If I understood correctly, you are asking if there is a functionality that listens to some event not triggered by a user command and takes action on it?

If so, no unfortunately not. However, I do not think it would be difficult to implement. I expect it would be a very welcome addition.

If you have the time to implement it and create a PR, I would be more than happy to review it and merge it.

**Comment by shomali11** [comment]
Actually come to think about it, you do not need `slacker` to expose new functionality to be able to accomplish what you need.

If your application wants to send messages to any channel, you could use the `Client` or `RTM`
https://github.com/shomali11/slacker/blob/master/slacker.go#L66-L74

They will give you all the functionality you need.
