### ISSUE TITLE
Slack API library

### ISSUE THREAD

**Issue by novln** [shomali11/slacker#59]
Hello :wave: 

Maybe a dumb question, but why this library isn't using the new (and maintained) https://github.com/slack-go/slack library, since `github.com/nlopes/slack` has moved.

Thank you in advance.

**Comment by shomali11** [comment]
Hello!

Not a dumb question at all. I just discovered that the underlying library changed recently. I will update it as soon as I have the chance unless you beat me to it :)

**Comment by shomali11** [comment]
And done!

Thank you for the reminder!

**Comment by novln** [comment]
Thank you :slightly_smiling_face:
