### ISSUE TITLE
This only works with "classic" slack apps

### ISSUE THREAD

**Issue by leetrout** [shomali11/slacker#63]
I think the README should be updated to indicate it uses the RTM API which does not function with new slack apps that have granular oauth permissions.

Took me 40 minutes to figure out what was going on by finally dropping the debug option in the config and seeing:

```
slack-go/slack2020/07/18 13:56:31 websocket_managed_conn.go:177: Connecting to RTM
slack-go/slack2020/07/18 13:56:32 rtm.go:71: Using URL:
slack-go/slack2020/07/18 13:56:32 websocket_managed_conn.go:181: Failed to start or connect to RTM: not_allowed_token_type
slack-go/slack2020/07/18 13:56:32 websocket_managed_conn.go:147: reconnection 1 failed: not_allowed_token_type reconnecting in 100ms
...
```

It is possible to still create apps that use the old permissions scopes but they are pushing everything to the events API.

More info in this thread https://github.com/slackapi/node-slack-sdk/issues/921#issuecomment-644317329

**Comment by shomali11** [comment]
Interesting. We will have to look into this further and see how it affects `slacker` and what we need to do to support both cases.

**Comment by leetrout** [comment]
> Interesting. We will have to look into this further and see how it affects `slacker` and what we need to do to support both cases.

I am happy to help out if you're willing to entertain supporting both APIs. You never know with various projects where they draw the line.

Would you entertain PRs or think you're going to do the work yourself?

**Comment by shomali11** [comment]
Absolutely! Some of the features here we suggested and/or created by awesome contributors!
I definitely think we need to support both APIs just in case somehow. The question is how to make it as easy and intuitive to the user of `slacker`

I did some research. At the time when `nlopes` started the `go-slack` project, there was only support for RTM and `slacker` was built on top of that (https://github.com/slack-go/slack/blob/master/examples/websocket/websocket.go)

It seems that `go-slack` now supports an Events API as seen here (https://github.com/slack-go/slack/blob/master/examples/eventsapi/events.go). I wonder if we can leverage this somehow.

**Comment by leetrout** [comment]
Yeah, it looks like there is a relatively straightforward path to combine the command definitions with the events as they show up. I'm excited because this will let it run in lambda / cloud functions, too :sunglasses:

**Comment by cameronbrill** [comment]
Checking to see if you guys are wanting to work on adding support to Events API. If so, I want to help out as well.

**Comment by shomali11** [comment]
@cameronbrill Create a PR! Any help is very much appreciated

**Comment by arusso** [comment]
With the introduction of [Socket-Mode](https://api.slack.com/apis/connections/socket) communication protocol and support for it being added to upstream in [slack-go](https://github.com/slack-go/slack/commit/483202e6be9328efbc6994beabb93e9a749408f6), I think that means we have all the pieces needed to use the Events API via Sockets-Mode.

**Comment by shomali11** [comment]
Awesome! Can you put a PR together?

**Comment by arusso** [comment]
Anything coming from me will take a while, as I am encumbered by policy and need to get approvals from my employer before I can contribute anything.

**Comment by paulkarayan** [comment]
Do you want a PR for updating the Readme? would have saved me an hour today :)

**Comment by tvhung83** [comment]
I hope you can update README, and/or log out fatal errors. It took me hours to figure out that it only supports legacy `bot` token (by enabling `DEBUG` mod).
