### ISSUE TITLE
Username retrieval

### ISSUE THREAD

**Issue by dmxrob** [shomali11/slacker#64]
I am trying to retrieve the username of the person talking to the bot, but have been unsuccessful.  I can get the userid, but not the name.  Is there any permission or other issues that you are aware of?

`sendSlackNotification(concatenated + "---" + botCtx.Event().Username + "---" + botCtx.Event().User)`

**Comment by shomali11** [comment]
I believe you will need to use the underlying `slack-go` library to get the "display name"
Example 7 shows you how to access the library https://github.com/shomali11/slacker/blob/master/examples/7/example7.go

This is the users file https://github.com/slack-go/slack/blob/master/users.go

**Comment by dmxrob** [comment]
Thanks man, appreciate it!
