### ISSUE TITLE
HandleMessage with prefixed messages, not just mention or direct message

### ISSUE THREAD

**Issue by icy95** [shomali11/slacker#69]
I was just trying to trigger the bot with !<COMMAND_NAME> like !catch etc. commands. However, messages handled for only mention or direct message for slack.MessageEvent case. How can we add any condition like isCommandPrefixMatch or sth like this ?

**Comment by arusso** [comment]
Now that slacker supports the Events API w/Socket Mode, this just works. Upgrade to the latest slacker (converting your bot to use Socket Mode) and ensure your app is subscribed to the right events (ie. `message.channels` for messages in a public channel) and then create a command like:

```
...
  bot.Command("!foo", &slacker.CommandDefinition{
    Handler: func(botCtx slacker.BotContext, request slacker.Request, response slacker.ResponseWriter) {
      response.Reply("pong")
    },
  })
...
```

**Comment by shomali11** [comment]
@icy95 Let us know if this solves your issue.

**Comment by arusso** [comment]
I believe the move to Events API / Socket Mode resolves this.
