### ISSUE TITLE
Support for Slash Commands

### ISSUE THREAD

**Issue by arusso** [shomali11/slacker#71]
Slack's [Slash Commands](https://api.slack.com/interactivity/slash-commands) offer another method of invoking some kind of action from within Slack, much like bot commands can do, but have the benefit of providing an arguably nicer user experience by pulling up a context pop up on how to invoke it, without requiring the user to memorize commands or to send a `help` message to a bot user.

Given the similarities between slacker's bot commands and slash commands, seems like a logical step to support both, and with Socket Mode support, we now have that option.

**Comment by a-nldisr** [comment]
This explains the following error I received while playing around, wish I knew this an hour ago:
```slack-go/slack/socketmode2021/08/07 18:44:54 slacker.go:213: unsupported Events API event received```

**Comment by josephlim75** [comment]
any timeline when this pull request will be merged to master ?

**Comment by arusso** [comment]
I believe we’re still waiting on the requested changes to be made. Once
those changes are made it shouldn’t take long to review.

Since this PR is stale you’re welcome to pick up the changes if the
original author isn’t interested.

**Comment by josephlim75** [comment]
There is a pull request at #88 , is there any pending development needs to be done for that pull request before being merged ?  If the answer is yes,  do you know what it is ?

**Comment by josephlim75** [comment]
So far, i have forked the latest master and add the changes that `ctennis` has done for PR #88.  I have been using that for slashcommand, it works so far and I haven't found any issue.

**Comment by arusso** [comment]
Resolved with #100 being merged.
