### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by mason-jones-ck** [shomali11/slacker#72]
Starting from your example, I'm testing a quick bot, but I'm getting an auth error. It's not clear from the code:

`bot := slacker.NewClient(os.Getenv("SLACK_BOT_TOKEN"), os.Getenv("SLACK_APP_TOKEN"))`

Whether this requires either a BOT token or an APP token, or if it needs both and what the difference is? For our Slack setup, I got an "API token" that should be a BOT token. When I set that and run it, I get:

> Connecting to Slack with Socket Mode.
> 2021/05/26 14:52:01 not_authed
> exit status 1

Just to check, I used the token as SLACK_APP_TOKEN and then it just repeats:

> Connecting to Slack with Socket Mode.
> Connection failed. Retrying later...

Over and over. 

It's not clear what the "not_authed" error means -- was the token refused, or did it fail to connect for authentication, or something else? Any hints on debugging this? Thank you!

**Comment by shomali11** [comment]
@arusso Could you help Mason figure out the auth issue he is facing please? 

Perhaps we should improve the README to clarify the new SocketMode changes

**Comment by mason-jones-ck** [comment]
Thanks for any help! In case it's useful, I figured out how to get it to run with debug=true and got this:
```
Connecting to Slack with Socket Mode.
slack-go/slack/socketmode2021/05/26 15:47:53 socket_mode_managed_conn.go:258: Starting SocketMode
slack-go/slack/socketmode2021/05/26 15:47:53 socket_mode_managed_conn.go:262: Failed to start or connect with SocketMode: not_authed
slack-go/slack/socketmode2021/05/26 15:47:53 socket_mode_managed_conn.go:210: invalid auth when connecting with SocketMode: not_authed
slack-go/slack/socketmode2021/05/26 15:47:53 socket_mode_managed_conn.go:78: Failed to connect with Socket Mode on try 0: not_authed
2021/05/26 15:47:53 not_authed
exit status 1
```

**Comment by arusso** [comment]
I’ll update the README this evening to describe how to create a new app or
move an existing legacy app.

Is this a new app or an existing one?

**Comment by arusso** [comment]
If your token begins with `xapp-` you have the app token, if your token looks like `xoxb-` you have the bot token.

I suspect you already have the app token since that one is front and center in the app page. Make sure you've done the following in your app config and then re-install your app to your workspace if you have to make any changes:

1. In `Event Subscriptions` subscribe to at least the `app_mention` (mentions) and/or `messages.im` (direct messages) events
2. In `Socket Mode`, enable Socket Mode
3. In `OAuth & Permissions`, add [scopes](https://api.slack.com/scopes) you need for your bot to function. At the top of this page you'll also find the Bot token.

After making any changes ensure you have re-installed your app to your workspace and then try and connect.

**Comment by mason-jones-ck** [comment]
Thanks very much for the info, I appreciate it. In this case I have an `xoxb-` token, so it is a bot token, not an app token. I'm a little constrained by my access, I can't create a Slack app, only a bot, so all I have is the API token.

If I need it to be a Slack App (I know they're deprecating bots), I can go the team here that owns our Slack setup and see about getting one created for me, but let me know if there's a way to make things work in a "bot-only" setup? Thanks again for your help.

**Comment by arusso** [comment]
As far as I know anyone should be able to [create an app](https://api.slack.com/apps), but you'll need to request to get it installed to your workspace which your slack admins will need to approve (they'll get a slack pop up asking them for approval).

That said if you can't create / use apps, you can pin to an older version of slacker (ie. 450dc60ca4cada1a4d4860d1a377949f9a950ba0) and continue using RTM.

**Comment by mason-jones-ck** [comment]
Thanks -- using an older version of slacker is an interesting idea, to at least do some initial experimentation while I look into creating an app. Our setup is very locked-down so I'll have to check whether apps will be approved or if I need to do some footwork first! Thanks again.

**Comment by mason-jones-ck** [comment]
Hello, I just wanted to confirm that after getting an app installed and generating the `xapp-` token, it appears to be working well. Thank you for the additional info you provided, which helped a lot.
