### ISSUE TITLE
Debugging why a response isn't being shown in Slack

### ISSUE THREAD

**Issue by mason-jones-ck** [shomali11/slacker#74]
I have a situation where I can see that my command is reaching the slackbot, and it is responding, but the response is not showing up in Slack. It's hard for me to tell if this is something wrong with the bot/slacker, or if it's something else, and I'm wonder if there are good strategies for debugging this? I'm happy to try things out and then add some documentation here via  PR with any helpful info I come up with.

Here's what I have so far:

I have put the "ping" command for testing, with a log line to show that the handler is getting executed -- it is:
```
definition := &slacker.CommandDefinition{
     Handler: func(botCtx slacker.BotContext, request slacker.Request, response slacker.ResponseWriter) {
          fmt.Println("I've been asked to ping-pong!")
          response.Reply("pong")
     },
}

bot.Command("ping", definition)
```

I've added debug(true) to the client:
```bot := slacker.NewClient(os.Getenv("SLACK_BOT_TOKEN"), os.Getenv("SLACK_APP_TOKEN"), slacker.WithDebug(true))```

When I start the bot, I see what I'd expect, although there is a message about `unsupported Events API event received`:

```
Connecting to Slack with Socket Mode.
slack-go/slack/socketmode2021/06/17 14:25:32 socket_mode_managed_conn.go:258: Starting SocketMode
slack-go/slack2021/06/17 14:25:32 socket_mode.go:30: Using URL: wss://wss-primary.slack.com/link/?ticket=<etc>
slack-go/slack/socketmode2021/06/17 14:25:32 socket_mode_managed_conn.go:266: Dialing to websocket on url wss://wss-primary.slack.com/link/?ticket=<etc>
slack-go/slack/socketmode2021/06/17 14:25:33 socket_mode_managed_conn.go:91: WebSocket connection succeeded on try 0
slack-go/slack/socketmode2021/06/17 14:25:33 socket_mode_managed_conn.go:439: Starting to receive message
Connected to Slack with Socket Mode.
slack-go/slack/socketmode2021/06/17 14:25:33 socket_mode_managed_conn.go:481: Incoming WebSocket message: {
  "type": "hello",
  "num_connections": 2,
  "debug_info": {
    "host": "applink-d85c5c684-wkb2x",
    "build_number": 18,
    "approximate_connection_time": 18060
  },
  "connection_info": {
    "app_id": "<id here>"
  }
}

slack-go/slack/socketmode2021/06/17 14:25:33 socket_mode_managed_conn.go:493: Finished to receive message
slack-go/slack/socketmode2021/06/17 14:25:33 socket_mode_managed_conn.go:439: Starting to receive message
slack-go/slack/socketmode2021/06/17 14:25:33 socket_mode_managed_conn.go:336: Received WebSocket message: {"type":"hello","num_connections":2,"debug_info":{"host":"applink-d85c5c684-wkb2x","build_number":18,"approximate_connection_time":18060},"connection_info":{"app_id":"<id here>"}}
slack-go/slack/socketmode2021/06/17 14:25:33 slacker.go:185: unsupported Events API event received
slack-go/slack/socketmode2021/06/17 14:25:38 socket_mode_managed_conn.go:561: WebSocket ping message received: Ping from applink-d85c5c684-wkb2x
```

When I chat with the bot in Slack and say "ping", I get no response, but I see this logged:

```
slack-go/slack/socketmode2021/06/17 14:28:25 socket_mode_managed_conn.go:493: Finished to receive message
slack-go/slack/socketmode2021/06/17 14:28:25 socket_mode_managed_conn.go:439: Starting to receive message
slack-go/slack/socketmode2021/06/17 14:28:25 socket_mode_managed_conn.go:336: Received WebSocket message: {"envelope_id":"9159361e-b381-4801-85a5-eedad48bc59a","payload":{"token":"<token>","team_id":"<id>","api_app_id":"<id>","event":{"client_msg_id":"e7d533c4-9442-4fac-8b86-cef8181f93b7","type":"message","text":"ping","user":"<user>","ts":"1623965305.000200","team":"<team>","blocks":[{"type":"rich_text","block_id":"ckcY","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"ping"}]}]}],"channel":"<channel>","event_ts":"1623965305.000200","channel_type":"im"},"type":"event_callback","event_id":"Ev025MBNNNLC","event_time":1623965305,"authorizations":[{"enterprise_id":null,"team_id":"<team>","user_id":"<user>","is_bot":true,"is_enterprise_install":false}],"is_ext_shared_channel":false,"event_context":"2-message-T065FDZTQ-A02305WBY31-D024FNJ3953"},"type":"events_api","accepts_response_payload":false,"retry_attempt":0,"retry_reason":""}
slack-go/slack/socketmode2021/06/17 14:28:25 socket_mode_managed_conn.go:430: Scheduling Socket Mode response for envelope ID 9159361e-b381-4801-85a5-eedad48bc59a: {"envelope_id":"9159361e-b381-4801-85a5-eedad48bc59a"}
slack-go/slack/socketmode2021/06/17 14:28:25 socket_mode_managed_conn.go:312: Sending Socket Mode response with envelope ID "9159361e-b381-4801-85a5-eedad48bc59a": &{9159361e-b381-4801-85a5-eedad48bc59a <nil>}
I've been asked to ping-pong!
slack-go/slack/socketmode2021/06/17 14:28:25 socket_mode_managed_conn.go:321: Finished sending Socket Mode response with envelope ID "9159361e-b381-4801-85a5-eedad48bc59a"
slack-go/slack2021/06/17 14:28:25 chat.go:233: Sending request: attachments=%5B%5D&blocks=%5B%5D&channel=<channel>&text=pong&token=<token>
```

(I have obviously taken out anything potentially sensitive/security-related)

Since I can see the response being sent, I'm not sure where to check next to see what the problem might be -- all of the connection, auth, etc seems fine. Any suggestions would be very much appreciated -- thanks for your help!

**Comment by mason-jones-ck** [comment]
Well, I discovered that somehow the wrong OAuth token got configured for the bot! I fixed that and responses are coming in now. In order to make this into a helpful thing, though: I would have expected to see some sort of auth error logged when it tried to send the response? I think slacker is calling `SendMessageContext()` to send, is that correct? Is it possible that the error response isn't being checked somehow?

Thanks again.

**Comment by arusso** [comment]
> somehow the wrong OAuth token got configured for the bot

Interesting, if you pass in the wrong app token you'll get an immediate failure, but a bad bot token doesn't and silently fails. I'm not sure if an error is actually returned anywhere such that we can catch this and fail early.

At the very least deserves a mention in a troubleshooting section.

**Comment by arusso** [comment]
I took a stab at clarifying the docs in #76 to help people troubleshoot this situation a bit faster.

I don't believe this is something we can detect automatically though since Slack isn't sending an invalid token message to us, and it behaves essentially like the app does not have any event subscriptions enabled.

**Comment by shomali11** [comment]
@mason-jones-ck Let us know if this clarifies the situation better.

**Comment by mason-jones-ck** [comment]
Yes, the mention of this in the troubleshooting docs definitely should help. Ideally of course there would be an error from `SendMessageContext()` that could bubble up to indicate there's an issue, but I know that might not be easy. Thank you for looking into it!

**Comment by arusso** [comment]
I can take a look again at the point where we send a message, I think I was focusing on the initial connection before, but it may be possible to detect at message send time.

**Comment by arusso** [comment]
I think what you're asking for is already happening.

In `Slack.PostMessage()` (used by the internal ResponseWriter's `Reply()` method) they [return any error it encounters](https://github.com/slack-go/slack/blob/158d3e0d1256ae0a169973da6eaaeb30b64a120b/chat.go#L130) which [`Reply()` then returns as well](https://github.com/shomali11/slacker/blob/master/response.go#L70).

I just tried that out by giving a bogus OAuth token to my bot and then checking the returned error:

```
...
	definition := &slacker.CommandDefinition{
		Handler: func(botCtx slacker.BotContext, request slacker.Request, response slacker.ResponseWriter) {
			err := response.Reply("pong")
			if err != nil {
				fmt.Printf("An error occurred: %v\n", err)
			}
		},
	}
...
````

When triggering the command, I can see it bubbles up the error as desired:

```
...
An error occurred: invalid_auth
...
```

**Comment by mason-jones-ck** [comment]
That's strange -- I wasn't seeing any error message, it just seemed to be failing silently. Interesting. That's good news, though!

**Comment by arusso** [comment]
Slacker's built-in ResponseWriter.Reply() method doesn't check any errors returned by the Slack library it just returns any it gets. So unless you were checking the returned error (and emitting your own message) in your CommandDefinition, you wouldn't see one.

**Comment by mason-jones-ck** [comment]
Ah, I see, yes. I'd have to go back to an earlier revision of the code to double-check, but I suspect you're right, it wasn't explicitly checking the err from response.Reply. I think I may have been mistakenly expecting the auth error to come from the slacker.NewClient() call instead. Thanks!
