### ISSUE TITLE
my app only responds to the 1st message i post

### ISSUE THREAD

**Issue by huaweiunity** [shomali11/slacker#75]
i copy the example go file, and wrote @app run, it only responds to the 1st mention. while if i register new command it respond again to the very 1st one. Any reason for this? thanks

**Comment by shomali11** [comment]
@arusso Could you please help figure this out?

**Comment by arusso** [comment]
Which example app are you copying?

**Comment by huaweiunity** [comment]
the 1st one, i just try to do ping pong. the dependency i am using is the lastest one.
func main() {
	bot := slacker.NewClient(os.Getenv("BotToken"), os.Getenv("AppToken"))

	definition := &slacker.CommandDefinition{
		Handler: func(botCtx slacker.BotContext, request slacker.Request, response slacker.ResponseWriter) {
			response.Reply("pong")
		},
	}

	bot.Command("run", definition)

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	err := bot.Listen(ctx)
	if err != nil {
		log.Fatal(err)
	}
}

**Comment by arusso** [comment]
What OAuth scopes do you have assigned to your bot?

The docs don't call these out (that's my bad, I should've included them) but I think these are a reasonable minimum (depending on your actually bot use case you may need more / less, but this should be enough for the example):

- app_mentions:read
- channels:history
- chat:write
- im:history
- im:write

If that doesn't work, can you try running this example w/debugging enabled to see what the bot is seeing / doing: https://gist.github.com/arusso/53415afe19bb85d3d01231d374423aa1#file-example1-w-debug-go

**Comment by huaweiunity** [comment]
i set a debugger to func (s *Slacker) Listen(ctx context.Context) error {. Looks like it doesn't listen the event i set.
The bot does reply to the first command i post, but then it is silent..

**Comment by huaweiunity** [comment]
and i thought i have all permissions above.

**Comment by huaweiunity** [comment]
```
slack-go/slack/socketmode2021/07/08 10:48:20 socket_mode_managed_conn.go:336: Received WebSocket message: {"envelope_id":"931fa9b9-de17-4c82-b98d-83c3cc504901","payload":{"token":"Fmb0jOg7evItFJN55b3lAO7n","team_id":"T06AF9667","enterprise_id":"E016WLPF0G6","api_app_id":"A027FMALDGU","event":{"client_msg_id":"0a66f6c9-1328-4ae3-8f05-a3a80eace3dc","type":"app_mention","text":"<@U026UTU9V5M>\u00a0ping","user":"U01HPSG52GN","ts":"1625712500.004100","team":"T06AF9667","blocks":[{"type":"rich_text","block_id":"5U2","elements":[{"type":"rich_text_section","elements":[{"type":"user","user_id":"U026UTU9V5M"},{"type":"text","text":"\u00a0ping"}]}]}],"channel":"C026FFKBZB9","event_ts":"1625712500.004100"},"type":"event_callback","event_id":"Ev027E8QLDSP","event_time":1625712500,"authorizations":[{"enterprise_id":"E016WLPF0G6","team_id":"T06AF9667","user_id":"U026UTU9V5M","is_bot":true,"is_enterprise_install":false}],"is_ext_shared_channel":false,"event_context":"2-app_mention-T06AF9667-A027FMALDGU-C026FFKBZB9"},"type":"events_api","accepts_response_payload":false,"retry_attempt":0,"retry_reason":""}
slack-go/slack/socketmode2021/07/08 10:48:20 socket_mode_managed_conn.go:430: Scheduling Socket Mode response for envelope ID 931fa9b9-de17-4c82-b98d-83c3cc504901: {"envelope_id":"931fa9b9-de17-4c82-b98d-83c3cc504901"}
slack-go/slack/socketmode2021/07/08 10:48:20 socket_mode_managed_conn.go:312: Sending Socket Mode response with envelope ID "931fa9b9-de17-4c82-b98d-83c3cc504901": &{931fa9b9-de17-4c82-b98d-83c3cc504901 <nil>}
slack-go/slack/socketmode2021/07/08 10:48:20 socket_mode_managed_conn.go:321: Finished sending Socket Mode response with envelope ID "931fa9b9-de17-4c82-b98d-83c3cc504901"
slack-go/slack/socketmode2021/07/08 10:48:27 socket_mode_managed_conn.go:561: WebSocket ping message received: Ping from applink-d85c5c684-chwqp
slack-go/slack/socketmode2021/07/08 10:48:37 socket_mode_managed_conn.go:561: WebSocket ping message received: Ping from applink-d85c5c684-chwqp
slack-go/slack/socketmode2021/07/08 10:48:47 socket_mode_managed_conn.go:561: WebSocket ping message received: Ping from applink-d85c5c684-chwqp
slack-go/slack/socketmode2021/07/08 10:48:57 socket_mode_managed_conn.go:561: WebSocket ping message received: Ping from applink-d85c5c684-chwqp
slack-go/slack/socketmode2021/07/08 10:49:03 socket_mode_managed_conn.go:481: Incoming WebSocket message: {
  "envelope_id": "dfddae8e-69df-4708-ae80-78cea9325b10",
  "payload": {
    "token": "Fmb0jOg7evItFJN55b3lAO7n",
    "team_id": "T06AF9667",
    "enterprise_id": "E016WLPF0G6",
    "api_app_id": "A027FMALDGU",
    "event": {
      "client_msg_id": "1df78fc1-6875-4d34-bb65-6be736cd20a1",
      "type": "app_mention",
      "text": "\u003c@U026UTU9V5M\u003e\u00a0ping",
      "user": "U01HPSG52GN",
      "ts": "1625712542.004300",
      "team": "T06AF9667",
      "blocks": [
        {
          "type": "rich_text",
          "block_id": "1rfr",
          "elements": [
            {
              "type": "rich_text_section",
              "elements": [
                {
                  "type": "user",
                  "user_id": "U026UTU9V5M"
                },
                {
                  "type": "text",
                  "text": "\u00a0ping"
                }
              ]
            }
          ]
        }
      ],
      "channel": "C026FFKBZB9",
      "event_ts": "1625712542.004300"
    },
    "type": "event_callback",
    "event_id": "Ev027SN35201",
    "event_time": 1625712542,
    "authorizations": [
      {
        "enterprise_id": "E016WLPF0G6",
        "team_id": "T06AF9667",
        "user_id": "U026UTU9V5M",
        "is_bot": true,
        "is_enterprise_install": false
      }
    ],
    "is_ext_shared_channel": false,
    "event_context": "2-app_mention-T06AF9667-A027FMALDGU-C026FFKBZB9"
  },
  "type": "events_api",
  "accepts_response_payload": false,
  "retry_attempt": 0,
  "retry_reason": ""
}
```

**Comment by huaweiunity** [comment]
looks like it's app mention message, but no response. Any idea???

**Comment by arusso** [comment]
`"text": "\u00a0ping"` seems to suggest you're getting more than just
`ping` in the message, which is causing it to not match and thus not
respond.

**Comment by huaweiunity** [comment]
thanks so much.. my fault

**Comment by huaweiunity** [comment]
btw, anyway i can intercept the command i received and trim the extra space?

**Comment by huaweiunity** [comment]
i think it's not the  request slacker.Request?? since the listener can't even listen the event

**Comment by arusso** [comment]
> btw, anyway i can intercept the command i received and trim the extra space?

I don't think there's an easy way to do that now. We'd either need to trim the command when we get it or the underlying command matching library would need to handle that.

> i think it's not the request slacker.Request?? since the listener can't even listen the event

I don't follow. Can you elaborate some more?

---

I'm trying to reproduce the issue on my end by triggering an app_mention event and I can't seem to do so. Using the example code I linked above, here's the event I see when I type `@my-bot-name ping`:

```
socketmode: 2021/07/07 21:22:43 socket_mode_managed_conn.go:336: Received WebSocket message: {"envelope_id":"dded50db-9c86-4d97-8c75-0d7845af31c2","payload":{"token":"hAcGSBFGqUqIoMGLBVor90ej","team_id":"T03MHJDDE","api_app_id":"A01T8J3FQH0","event":{"client_msg_id":"260e4aed-40f3-43bb-bd77-15c0158aa434","type":"app_mention","text":"<@U01T8J8NG1Y> ping","user":"U03MHJDDL","ts":"1625718163.000200","team":"T03MHJDDE","blocks":[{"type":"rich_text","block_id":"3UD","elements":[{"type":"rich_text_section","elements":[{"type":"user","user_id":"U01T8J8NG1Y"},{"type":"text","text":" ping"}]}]}],"channel":"C01TB3ZTQ2W","event_ts":"1625718163.000200"},"type":"event_callback","event_id":"Ev0283TNKQM6","event_time":1625718163,"authorizations":[{"enterprise_id":null,"team_id":"T03MHJDDE","user_id":"U01T8J8NG1Y","is_bot":true,"is_enterprise_install":false}],"is_ext_shared_channel":false,"event_context":"2-app_mention-T03MHJDDE-A01T8J3FQH0-C01TB3ZTQ2W"},"type":"events_api","accepts_response_payload":false,"retry_attempt":0,"retry_reason":""}
```

And the bot responds as expected with `pong`:

```
slack-go/slack/socketmode2021/07/07 21:24:39 socket_mode_managed_conn.go:481: Incoming WebSocket message: {
  "envelope_id": "268cff26-dcbc-44b5-ac71-3f46037b3aa5",
  "payload": {
    "token": "hAcGSBFGqUqIoMGLBVor90ej",
    "team_id": "T03MHJDDE",
    "api_app_id": "A01T8J3FQH0",
    "event": {
      "bot_id": "B01TYCD7VA4",
      "type": "message",
      "text": "pong",
      "user": "U01T8J8NG1Y",
      "ts": "1625718279.003300",
      "team": "T03MHJDDE",
      "bot_profile": {
        "id": "B01TYCD7VA4",
        "deleted": false,
        "name": "Slacker Socket Mode",
        "updated": 1617562219,
        "app_id": "A01T8J3FQH0",
        "icons": {
          "image_36": "https:\/\/a.slack-edge.com\/80588\/img\/plugins\/app\/bot_36.png",
          "image_48": "https:\/\/a.slack-edge.com\/80588\/img\/plugins\/app\/bot_48.png",
          "image_72": "https:\/\/a.slack-edge.com\/80588\/img\/plugins\/app\/service_72.png"
        },
        "team_id": "T03MHJDDE"
      },
      "channel": "D01TYCD7ZBJ",
      "event_ts": "1625718279.003300",
      "channel_type": "im"
    },
    "type": "event_callback",
    "event_id": "Ev027LDE1A1J",
    "event_time": 1625718279,
    "authorizations": [
      {
        "enterprise_id": null,
        "team_id": "T03MHJDDE",
        "user_id": "U01T8J8NG1Y",
        "is_bot": true,
        "is_enterprise_install": false
      }
    ],
    "is_ext_shared_channel": false,
    "event_context": "2-message-T03MHJDDE-A01T8J3FQH0-D01TYCD7ZBJ"
  },
  "type": "events_api",
  "accepts_response_payload": false,
  "retry_attempt": 0,
  "retry_reason": ""
}
```

Worth mentioning that depending on your scopes, this actually results in TWO events, one `app_mention` AND one `message` (from the channel:history scope, I think).

**Comment by huaweiunity** [comment]
i mean can I preprocess the requests to trim the space it posts?
I copy paste the command I type, it will send out this "`"text": "\u00a0ping"`"

**Comment by arusso** [comment]
> i mean can I preprocess the requests to trim the space it posts?

No

---

I'm baffled a bit by this to be honest, I'm unable to re-produce the input where the unicode code point is introduce, which seems to be tripping up the command matching function. Are you using the official Slack desktop/mobile app or the browser or some other app?

I'm not sure what else you can try to be honest. Your event subscriptions are obviously correct or you wouldn't be getting the event to begin with. You might check your OAuth scopes and ensure you have `chat:write` associated with your app.

**Comment by huaweiunity** [comment]
if i just type @app run, it works:). but if i copy paste the previous command i run, it will comes with that strange char. So wondering if i can preprocess the image or you can patch this into the module

I am using official Slack in an Enterprise. My permission definitly correct, since it's working now.... just copy paste gave me that char:)


thanks so much for your help

**Comment by arusso** [comment]
Odd, I tried that too but couldn’t reproduce it. Glad it works when it’s
typed out though!

**Comment by huaweiunity** [comment]
ok. thanks for saving me tons of time anyway:)
