### ISSUE TITLE
Allow overriding command constructor

### ISSUE THREAD

**Issue by asafalima** [shomali11/slacker#97]
Add the option for the user to provide a custom command constructor.
This can be used to prefix all commands with the bot name to make the bot respond to messages without proper Slack mention (for example instead of `@MyBot ping` you can make it listen to all messages in the channel, add the name prefix to the command and invoke `mybot ping`)
In out use case we need it to pass customize the creation of the commander command (See https://github.com/shomali11/commander/pull/3).

**Comment by arusso** [comment]
Fixed in #104
